"""
Alert Models

Models for the domain-specific alerting system.
Alerts are generated by server-side rules for:
- RED issues unresolved for N days
- VAT anomalies detected during REVIEW
- Attempted posting into FINALIZED/LOCKED period
- Document backlog above threshold
- Failed background operations
"""
import uuid
from datetime import datetime
from sqlalchemy import String, DateTime, func, ForeignKey, Text, Boolean, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
import enum

from app.core.database import Base


class AlertSeverity(str, enum.Enum):
    """Alert severity levels."""
    CRITICAL = "CRITICAL"  # Immediate action required
    WARNING = "WARNING"    # Attention soon
    INFO = "INFO"         # Informational


class AlertCode(str, enum.Enum):
    """Predefined alert codes for domain-specific rules."""
    # Issue-related
    RED_ISSUE_UNRESOLVED = "RED_ISSUE_UNRESOLVED"
    YELLOW_ISSUE_BACKLOG = "YELLOW_ISSUE_BACKLOG"
    
    # VAT-related
    VAT_ANOMALIES_DETECTED = "VAT_ANOMALIES_DETECTED"
    VAT_DEADLINE_APPROACHING = "VAT_DEADLINE_APPROACHING"
    
    # Period-related
    POSTING_TO_FINALIZED_PERIOD = "POSTING_TO_FINALIZED_PERIOD"
    POSTING_TO_LOCKED_PERIOD = "POSTING_TO_LOCKED_PERIOD"
    PERIOD_LOCK_PENDING = "PERIOD_LOCK_PENDING"
    
    # Document-related
    DOCUMENT_BACKLOG_HIGH = "DOCUMENT_BACKLOG_HIGH"
    DOCUMENT_PROCESSING_FAILED = "DOCUMENT_PROCESSING_FAILED"
    DOCUMENT_STUCK_PROCESSING = "DOCUMENT_STUCK_PROCESSING"
    
    # System-related
    BACKGROUND_OPERATION_FAILED = "BACKGROUND_OPERATION_FAILED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    SYSTEM_HEALTH_DEGRADED = "SYSTEM_HEALTH_DEGRADED"


class Alert(Base):
    """
    Domain-specific alerts for accountant ops control.
    
    Alerts are generated by server-side rules and stored for
    dashboard display. No email/SMS - in-app only.
    """
    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    administration_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("administrations.id", ondelete="CASCADE"), nullable=True
    )
    alert_code: Mapped[str] = mapped_column(String(100), nullable=False)
    severity: Mapped[AlertSeverity] = mapped_column(
        SQLEnum(AlertSeverity), nullable=False
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    
    # References to related entities (for linking in UI)
    entity_type: Mapped[str] = mapped_column(String(50), nullable=True)  # document, journal_entry, period, issue
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=True)
    
    # Metadata
    context: Mapped[str] = mapped_column(Text, nullable=True)  # JSON string with additional context
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    acknowledged_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    acknowledged_by_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    resolved_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_by_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    resolution_notes: Mapped[str] = mapped_column(Text, nullable=True)
    
    # Auto-resolution tracking
    auto_resolved: Mapped[bool] = mapped_column(Boolean, default=False)

    # Relationships
    administration = relationship("Administration", back_populates="alerts")
    acknowledged_by = relationship("User", foreign_keys=[acknowledged_by_id])
    resolved_by = relationship("User", foreign_keys=[resolved_by_id])
    
    @property
    def is_active(self) -> bool:
        """Check if alert is still active (not resolved)."""
        return self.resolved_at is None
    
    @property
    def is_acknowledged(self) -> bool:
        """Check if alert has been acknowledged."""
        return self.acknowledged_at is not None
